# 2024-06-03.23-1 Adam 
reference_id:
  GCF_000022665.1

# TSV of input files
# The columns are
# 1. Path to forward reads
# 2. Path to reverse reads
# 3. Sample name
input:
  "input.tsv"

results:
  "results"

pval: 0.01 # SNP p-value
freq: 0.1  # SNP frecuency

bowtie_threads:
 "all" # all or int
