# RefSeq ID of reference genome
reference_id:
  "GCA_013166975.1" # BL12 e. coli

names:
  "tests/test1/input_names.txt"
forwards:
  "tests/test1/input_forwards.txt"
reverses:
  "tests/test1/input_reverses.txt"

out_results:
  "results_test/test1"
out_alignments:
  "results_test/test1/alignments"
out_reference:
  "results_test/test1/reference"

bowtie2_threads: 12

variants_pval: 0.01
variants_freq: 0.1
